#!/bin/bash

# setting limit to 0 == no limit
PROCESSING_LIMIT=$1
YEAR=$2
MONTH=$3
LOCAL_TARGET=./raw_files/$YEAR/$MONTH

echo "STARTING download from Wikimedia and load into S3 for $YEAR-$MONTH with processing limit of $PROCESSING_LIMIT" `date -u --rfc-822`

rm -r $LOCAL_TARGET
mkdir ./raw_files ./raw_files/$YEAR $LOCAL_TARGET
rm ./logs/download$YEAR$MONTH.log

   echo "Processing $y month $m"
   mvn exec:java -Dexec.mainClass="org.commonvox.bigdatademos.WikimediaFileDownloaderMonthly" -Dexec.args="https://dumps.wikimedia.org/other/pageviews/$YEAR/$YEAR-$MONTH/ $LOCAL_TARGET/ $PROCESSING_LIMIT" >> ./logs/download$YEAR$MONTH.log
   aws s3 cp $LOCAL_TARGET/ s3://wmf-insight-datalake/raw_files/$YEAR/ --recursive
   rm ./raw_files/$YEAR/$MONTH/*.*

echo "COMPLETED download processing for $YEAR-$MONTH: " `date -u --rfc-822`
