#!/bin/bash

YEAR=$1

echo "Removing existing HDFS data"
hadoop fs -rm -r /test/

echo "Recreating HDFS directory and subdirectories"
hadoop fs -mkdir /test /test/raw_files

rm -r ./raw_files
mkdir ./raw_files
rm ./logs/hdfs_move.log

echo "STARTING download from S3 and load into HDFS for $YEAR" `date -u --rfc-822`

aws s3 cp s3://wmf-insight-datalake/raw_files/$YEAR/ ./raw_files/ --recursive
hadoop fs -moveFromLocal ./raw_files/*.* /test/raw_files > ./logs/hdfs_move.log
rm ./raw_files/*.*

echo "COMPLETED download from S3 and load into HDFS for $YEAR" `date -u --rfc-822`

