#!/bin/bash

rm ./downloaded_files/*.*
rm -r ./downloaded_files
mkdir ./downloaded_files
rm -r ./reorg
mkdir ./reorg
mkdir ./reorg/2015
rm ./logs/s3_download.log
rm ./logs/s3_upload.log

echo "STARTING reorg of S3 for 2015 months 06 thru 12" `date -u --rfc-822`

echo "Downloading 2015 month $m files from S3"
aws s3 cp s3://wmf-insight-datalake/raw_files/2015/ ./downloaded_files/ --recursive  > ./logs/s3_reorg.log 2>&1

for m in {06..12}
do
   echo "Reorganizing of 2015 month $m"
   mkdir ./reorg/2015/$m
   mv ./downloaded_files/pageviews-2015$m*.gz ./reorg/2015/$m/
done

echo "Uploading reorganized files back to S3 for 2015" `date -u --rfc-822`
for m in {06..12}
do
   echo "Uploading reorg of 2015 month $m"
   aws s3 cp ./reorg/2015/$m s3://wmf-insight-datalake/pageviews/2015/$m --recursive >> ./logs/s3_reorg.log 2>&1
done

echo "Removing local reorg files"
rm -r ./reorg
rm ./downloaded_files/*.*
rm -r ./downloaded_files

echo "COMPLETED reorg of S3 for 2015 months 06 thru 12" `date -u --rfc-822`

