#!/bin/bash

YEAR=$1

rm -r ./downloaded_files
mkdir ./downloaded_files
rm -r ./reorg
mkdir ./reorg
mkdir ./reorg/$YEAR
rm ./logs/s3_download.log
rm ./logs/s3_upload.log

echo "STARTING reorg of S3 for $YEAR" `date -u --rfc-822`

echo "Downloading $YEAR month $m files from S3"
# aws s3 cp s3://wmf-insight-datalake/raw_files/$YEAR/ ./downloaded_files/ --recursive  > ./logs/s3_reorg.log 2>&1

for m in {01..12}
do
   echo "Reorganizing of $YEAR month $m"
   mkdir ./reorg/$YEAR/$m
#   mv ./downloaded_files/pageviews-$YEAR$m*.* ./reorg/$YEAR/$m/
done

echo "Uploading reorganized files back to S3 for $YEAR" `date -u --rfc-822`
for m in {01..12}
do
   echo "Uploading reorg of $YEAR month $m"
#   aws s3 cp ./reorg/$YEAR/$m s3://wmf-insight-datalake/pageviews/$YEAR/$m --recursive >> ./logs/s3_reorg.log 2>&1
done

echo "Removing local reorg files"
# rm -r ./reorg

echo "COMPLETED reorg of S3 for $YEAR" `date -u --rfc-822`

